name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Inkscape Repo
        run: "sudo add-apt-repository ppa:inkscape.dev/stable"
      - name: Update sudo
        run: "sudo apt update"
      - name: Install Inkscape
        run: "sudo apt install inkscape"
      - name: Convert SVG
        run: " inkscape -D orbitals.svg  -o orbitals.pdf --without-gui --export-latex"
        
      # Runs a single command using the runners shell
      - name: LaTeX Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
          post_compile: "latexmk -c"
          latexmk_shell_escape: true
      - name: GitHub Commit & Push
  # You may pin to the exact commit or the version.
  # uses: actions-js/push@4decc2887d2770f29177082be3c8b04d342f5b64
        uses: actions-js/push@v1.2
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: $\{{ secrets.LATEX_COMPILE}}
          # Email used to configure user.email in `git config`.
          # Email used to make a co-authored commit.
          coauthor_email: salil.gokhale.mt121@maths.iitd.ac.in
          # Name used to make a co-authored commit.
          coauthor_name: Salil03
          # Commit message.
          message: Auto-latex Build
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})

          # Destination branch to push changes

          # Allow empty commit
          empty: false
